name: triplespec_focus
dependencies:
  - python=3.10
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - ccdproc
      - coveralls
      - sphinx_rtd_theme
      - sphinx
      - sphinxcontrib.napoleon